// <auto-generated />
using System;
using JsonToDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JsonToDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200420095714_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JsonToDb.Model.Country", b =>
                {
                    b.Property<string>("GeoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerrorityCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeoId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("JsonToDb.Model.DailyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cases")
                        .HasColumnType("int");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<string>("PopData2018")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("DailyData");
                });

            modelBuilder.Entity("JsonToDb.Model.DailyData", b =>
                {
                    b.HasOne("JsonToDb.Model.Country", "Country")
                        .WithMany("DailyDataCollection")
                        .HasForeignKey("CountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
